### ISSUE TITLE
Error running GUI program on windows

### ISSUE THREAD

**Issue by elpreto** [AZn5ReD/saplearninghub-pdf-downloader-gui#11]
Hi.
I downloaded the app for windows, and I get this error.
I changed the email address for privacy.

Starting script...
(node:20020) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Going to: https://learninghub.sap.com/login
Entering login: mail@mail.com  **--> edited by me to hide email address**
Entering password: ***
Error during login: Error: Execution context was destroyed, most likely because of a navigation.
    at P (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:60512)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async n.ExecutionContext._evaluateInternal (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:60018)
    at async o.evaluateHandle (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:20934)
    at async o.$ (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:27288)
    at async DOMWorld.$ (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:1078210)
    at async DOMWorld.type (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:1081772)
  -- ASYNC --
    at n.ExecutionContext.<anonymous> (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:7836)
    at o.evaluateHandle (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:20964)
    at o.<anonymous> (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:7859)
    at o.$ (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:27299)
    at o.<anonymous> (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:7859)
    at DOMWorld.$ (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:1078218)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async DOMWorld.type (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:1081772)
  -- ASYNC --
    at f.<anonymous> (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:7836)
    at W.type (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:55697)
    at D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:18:847502
    at s (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:1024897)
    at Generator._invoke (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:1024650)
    at Generator.forEach.e.<computed> [as next] (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:1025254)
    at t (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:12899)
    at c (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:13110)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
Error: Error during init
    at D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:18:854325
    at s (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:1024897)
    at Generator._invoke (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:1024650)
    at Generator.forEach.e.<computed> [as next] (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:1025254)
    at t (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:12899)
    at c (D:\Documents\Downloads\saplearninghub-pdf-downloader-gui\index.js:1:13110)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

**Comment by AZn5ReD** [comment]
It happens to me too sometimes. I don't know where that comes from.
Usually, I start again and it works. Could you try again ?

**Comment by elpreto** [comment]
Hi.

Thank you for the quick reply!

I've tried several times, but it always fails.

Is it better if I try on linux? Even the no-gui doesn't work for me, I cannot compile.
