### ISSUE TITLE
Error running GUI program on Linux (Kubuntu 20.10)

### ISSUE THREAD

**Issue by elpreto** [AZn5ReD/saplearninghub-pdf-downloader-gui#12]
Hi.

This is the error I get trying on Linux.

internal/modules/cjs/loader.js:1188
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /tmp/.mount_sapleaqtzcA9/dist/nodegui_core-26b59b5128dd2adbc630e7f87fe8fcb6.node: undefined symbol: _ZN4qode9qode_argvE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/.mount_sapleaqtzcA9/dist/index.js:1:124260)
    at n (/tmp/.mount_sapleaqtzcA9/dist/index.js:1:110)
    at Object.<anonymous> (/tmp/.mount_sapleaqtzcA9/dist/index.js:1:1000)
    at n (/tmp/.mount_sapleaqtzcA9/dist/index.js:1:110)
    at Object.<anonymous> (/tmp/.mount_sapleaqtzcA9/dist/index.js:1:1191)
internal/modules/cjs/loader.js:1188
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

**Comment by AZn5ReD** [comment]
What are the input values ? (don't send your credentials)
