### ISSUE TITLE
Tested on 28/11/2020 got error

### ISSUE THREAD

**Issue by bravemanvvn** [AZn5ReD/saplearninghub-pdf-downloader-gui#13]
I tested with windows 10, Centos8, Ubuntu 20, Macos 10.14
It's got same error both gui version and not gui version.
https://github.com/AZn5ReD/saplearninghub-pdf-downloader
https://github.com/AZn5ReD/saplearninghub-pdf-downloader-gui
Windows 10, Centos, Ubuntu ( updated lastest ) with chrome version 87, nodejs version v14.15.1.
book link : https://saplearninghub.plateau.com/icontent_e/CUSTOM_eu/sap/self-managed/ebook/TERP10_RU_Col17/index.html
Please help me fix it, thanks you so much !

############ERROR ON WINDOWS 10 & CENTOS8 WITH GUI VERSION############
Starting script...
(node:9244) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Going to: https://learninghub.sap.com/login
Entering login: S002075XXXX
Entering password: ***
Error during login: Error: Execution context was destroyed, most likely because of a navigation.
    at P (C:\saplearninghub-pdf-downloader-gui\index.js:1:60512)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async n.ExecutionContext._evaluateInternal (C:\saplearninghub-pdf-downloader-gui\index.js:1:60018)
    at async o.evaluateHandle (C:\saplearninghub-pdf-downloader-gui\index.js:1:20934)
    at async o.$ (C:\saplearninghub-pdf-downloader-gui\index.js:1:27288)
    at async DOMWorld.$ (C:\saplearninghub-pdf-downloader-gui\index.js:1:1078210)
    at async DOMWorld.type (C:\saplearninghub-pdf-downloader-gui\index.js:1:1081772)
  -- ASYNC --
    at n.ExecutionContext.<anonymous> (C:\saplearninghub-pdf-downloader-gui\index.js:1:7836)
    at o.evaluateHandle (C:\saplearninghub-pdf-downloader-gui\index.js:1:20964)
    at o.<anonymous> (C:\saplearninghub-pdf-downloader-gui\index.js:1:7859)
    at o.$ (C:\saplearninghub-pdf-downloader-gui\index.js:1:27299)
    at o.<anonymous> (C:\saplearninghub-pdf-downloader-gui\index.js:1:7859)
    at DOMWorld.$ (C:\saplearninghub-pdf-downloader-gui\index.js:1:1078218)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DOMWorld.type (C:\saplearninghub-pdf-downloader-gui\index.js:1:1081772)
  -- ASYNC --
    at f.<anonymous> (C:\saplearninghub-pdf-downloader-gui\index.js:1:7836)
    at W.type (C:\saplearninghub-pdf-downloader-gui\index.js:1:55697)
    at C:\saplearninghub-pdf-downloader-gui\index.js:18:847502
    at s (C:\saplearninghub-pdf-downloader-gui\index.js:1:1024897)
    at Generator._invoke (C:\saplearninghub-pdf-downloader-gui\index.js:1:1024650)
    at Generator.forEach.e.<computed> [as next] (C:\saplearninghub-pdf-downloader-gui\index.js:1:1025254)
    at t (C:\saplearninghub-pdf-downloader-gui\index.js:1:12899)
    at c (C:\saplearninghub-pdf-downloader-gui\index.js:1:13110)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Error during init
    at C:\saplearninghub-pdf-downloader-gui\index.js:18:854325
    at s (C:\saplearninghub-pdf-downloader-gui\index.js:1:1024897)
    at Generator._invoke (C:\saplearninghub-pdf-downloader-gui\index.js:1:1024650)
    at Generator.forEach.e.<computed> [as next] (C:\saplearninghub-pdf-downloader-gui\index.js:1:1025254)
    at t (C:\saplearninghub-pdf-downloader-gui\index.js:1:12899)
    at c (C:\saplearninghub-pdf-downloader-gui\index.js:1:13110)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

########################ERROR BY COMMAND PROJECT VERSION########################
npm run start
> saplearninghub-pdf-downloader@1.0.0 start C:\saplearninghub-pdf-downloader
> set NODE_ENV=production && node ./dist/index.js
Starting script...
(node:10248) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Going to: https://learninghub.sap.com/login
Entering login: S002075XXXX
Entering password: ***
Submiting...
Redirected to: https://accounts.sap.com/saml2/idp/sso
Redirected to: https://learninghub.sap.com/saml2/sp/acs/a00026fd2/a00026fd2
Connected :)
No cookie consent
Navigating to SuccessFactor
Redirected to: https://learninghub.sap.com/?languagePrompt=true
Redirected to: https://performancemanager.successfactors.eu/sf/options?bplte_company=learninghub&_s.crb=P389hNH0UZDeVy6xCC5ySFxyCXI%3d
Error while navToSF r: Navigation timeout of 30000 ms exceeded
    at C:\saplearninghub-pdf-downloader\dist\index.js:1:885171
    at async FrameManager.waitForFrameNavigation (C:\saplearninghub-pdf-downloader\dist\index.js:1:879560)
    at async f.waitForNavigation (C:\saplearninghub-pdf-downloader\dist\index.js:1:874398)
    at async W.waitForNavigation (C:\saplearninghub-pdf-downloader\dist\index.js:1:50230)
  -- ASYNC --
    at f.<anonymous> (C:\saplearninghub-pdf-downloader\dist\index.js:1:7836)
    at W.waitForNavigation (C:\saplearninghub-pdf-downloader\dist\index.js:1:50267)
    at W.<anonymous> (C:\saplearninghub-pdf-downloader\dist\index.js:1:7859)
    at C:\saplearninghub-pdf-downloader\dist\index.js:18:940321
    at s (C:\saplearninghub-pdf-downloader\dist\index.js:1:1067554)
    at Generator._invoke (C:\saplearninghub-pdf-downloader\dist\index.js:1:1067307)
    at Generator.forEach.e.<computed> [as next] (C:\saplearninghub-pdf-downloader\dist\index.js:1:1067911)
    at t (C:\saplearninghub-pdf-downloader\dist\index.js:1:12899)
    at c (C:\saplearninghub-pdf-downloader\dist\index.js:1:13110)
    at C:\saplearninghub-pdf-downloader\dist\index.js:1:13169
  -- ASYNC --
    at W.<anonymous> (C:\saplearninghub-pdf-downloader\dist\index.js:1:7836)
    at C:\saplearninghub-pdf-downloader\dist\index.js:18:940321
    at s (C:\saplearninghub-pdf-downloader\dist\index.js:1:1067554)
    at Generator._invoke (C:\saplearninghub-pdf-downloader\dist\index.js:1:1067307)
    at Generator.forEach.e.<computed> [as next] (C:\saplearninghub-pdf-downloader\dist\index.js:1:1067911)
    at t (C:\saplearninghub-pdf-downloader\dist\index.js:1:12899)
    at c (C:\saplearninghub-pdf-downloader\dist\index.js:1:13110)
    at C:\saplearninghub-pdf-downloader\dist\index.js:1:13169
    at new Promise (<anonymous>)
    at C:\saplearninghub-pdf-downloader\dist\index.js:1:13050
Initialize file
URL Template: https://saplearninghub.plateau.com/icontent_e/CUSTOM_eu/sap/self-managed/ebook/TERP10_RU_Col17/xml/topic$$$.svg
File path: C:\saplearninghub-pdf-downloader/TERP10_RU_Col17.pdf
r: waiting for selector "#progressIndicator" failed: timeout 30000ms exceeded
    at new P (C:\saplearninghub-pdf-downloader\dist\index.js:1:1118196)
    at DOMWorld._waitForSelectorOrXPath (C:\saplearninghub-pdf-downloader\dist\index.js:1:1124964)
    at DOMWorld.waitForSelector (C:\saplearninghub-pdf-downloader\dist\index.js:1:1124552)
    at f.waitForSelector (C:\saplearninghub-pdf-downloader\dist\index.js:1:875992)
    at f.<anonymous> (C:\saplearninghub-pdf-downloader\dist\index.js:1:7859)
    at W.waitForSelector (C:\saplearninghub-pdf-downloader\dist\index.js:1:57055)
    at C:\saplearninghub-pdf-downloader\dist\index.js:18:944809
    at s (C:\saplearninghub-pdf-downloader\dist\index.js:1:1067554)
    at Generator._invoke (C:\saplearninghub-pdf-downloader\dist\index.js:1:1067307)
    at Generator.forEach.e.<computed> [as next] (C:\saplearninghub-pdf-downloader\dist\index.js:1:1067911)
  -- ASYNC --
    at f.<anonymous> (C:\saplearninghub-pdf-downloader\dist\index.js:1:7836)
    at W.waitForSelector (C:\saplearninghub-pdf-downloader\dist\index.js:1:57055)
    at C:\saplearninghub-pdf-downloader\dist\index.js:18:944809
    at s (C:\saplearninghub-pdf-downloader\dist\index.js:1:1067554)
    at Generator._invoke (C:\saplearninghub-pdf-downloader\dist\index.js:1:1067307)
    at Generator.forEach.e.<computed> [as next] (C:\saplearninghub-pdf-downloader\dist\index.js:1:1067911)
    at t (C:\saplearninghub-pdf-downloader\dist\index.js:1:12899)
    at c (C:\saplearninghub-pdf-downloader\dist\index.js:1:13110)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by AZn5ReD** [comment]
Could you please download the release again, I put the wrong release file from the original repo. It should work now.

**Comment by bravemanvvn** [comment]
@AZn5ReD 
Thanks for your reply,
Now, I'm test againt with both version ( gui and without gui) got same new trouble :Can't find SuccessFactor Link.

Starting script...
(node:173782) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Going to: https://learninghub.sap.com/login
Entering login: S0020751444
Entering password: ***
Submiting...
Redirected to: https://accounts.sap.com/saml2/idp/sso
Redirected to: https://learninghub.sap.com/saml2/sp/acs/a00026fd2/a00026fd2
Connected :)
No cookie consent
Navigating to SuccessFactor
Can't find SuccessFactor Link
Initialize file
URL Template: https://saplearninghub.plateau.com/icontent_e/CUSTOM_eu/sap/self-managed/ebook/ADM900_EN_Col19/xml/topic$$$.svg
File path: /opt/SAPebook/ADM900_EN_Col19.pdf
{ r: waiting for selector "#progressIndicator" failed: timeout 30000ms exceeded
    at new P (/opt/saplearninghub-pdf-downloader/dist/index.js:1:1118194)
    at DOMWorld._waitForSelectorOrXPath (/opt/saplearninghub-pdf-downloader/dist/index.js:1:1124962)
    at DOMWorld.waitForSelector (/opt/saplearninghub-pdf-downloader/dist/index.js:1:1124550)
    at f.waitForSelector (/opt/saplearninghub-pdf-downloader/dist/index.js:1:875992)
    at f.<anonymous> (/opt/saplearninghub-pdf-downloader/dist/index.js:1:7859)
    at W.waitForSelector (/opt/saplearninghub-pdf-downloader/dist/index.js:1:57055)
    at /opt/saplearninghub-pdf-downloader/dist/index.js:18:944809
    at s (/opt/saplearninghub-pdf-downloader/dist/index.js:1:1067552)
    at Generator._invoke (/opt/saplearninghub-pdf-downloader/dist/index.js:1:1067305)
    at Generator.forEach.e.(anonymous function) [as next] (/opt/saplearninghub-pdf-downloader/dist/index.js:1:1067909)
  -- ASYNC --
    at f.<anonymous> (/opt/saplearninghub-pdf-downloader/dist/index.js:1:7836)
    at W.waitForSelector (/opt/saplearninghub-pdf-downloader/dist/index.js:1:57055)
    at /opt/saplearninghub-pdf-downloader/dist/index.js:18:944809
    at s (/opt/saplearninghub-pdf-downloader/dist/index.js:1:1067552)
    at Generator._invoke (/opt/saplearninghub-pdf-downloader/dist/index.js:1:1067305)
    at Generator.forEach.e.(anonymous function) [as next] (/opt/saplearninghub-pdf-downloader/dist/index.js:1:1067909)
    at t (/opt/saplearninghub-pdf-downloader/dist/index.js:1:12899)
    at c (/opt/saplearninghub-pdf-downloader/dist/index.js:1:13110)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'r' }

**Comment by AZn5ReD** [comment]
I suspect that you're not on the same server as me. I'm on EU server and I hardcoded the link to access to the hub.
Could you please send me the link behind the "learning content" ?
![image](https://user-images.githubusercontent.com/1781837/101838683-5e8acd80-3b41-11eb-87e5-bd435ea6a905.png)

**Comment by bravemanvvn** [comment]
Dear Mr @AZn5ReD 
I'm test againt with both latest version ( gui and without gui) got same previous trouble "File path: C:\SAP-Ebook\saplearninghub-pdf-downloader-gui/ADM900_EN_Col19.pdfError while navToSF TimeoutError: Navigation timeout of 30000 ms exceeded"

I'm connect on Southeast Asia, I think SAP learning only one location on EU.
I use web browser login link https://performancemanager.successfactors.eu/sf/home?bplte_company=learninghub&_s.crb=0mN%252fTd%252fNS8vG8Ku6egOT3Mq%252bv4R%252bXQKzSB8C0t%252btJdo%253d#Shell-home
Ebook link : https://saplearninghub.plateau.com/icontent_e/CUSTOM_eu/sap/self-managed/ebook/ADM900_EN_Col19/index.html

from you reply on 5 December : "Could you please download the release again, I put the wrong release file from the original repo. It should work now."
Why the latest github version ( 1.0.1) release at Oct 15 ? ( I check all file saplearninghub-pdf-downloader-gui-1.0.1-windows-x64.zip and all file on your github project are older than December 10th)

Thank you so much !

**Comment by AZn5ReD** [comment]
> Why the latest github version ( 1.0.1) release at Oct 15 ? ( I check all file saplearninghub-pdf-downloader-gui-1.0.1-windows-x64.zip and all file on your github project are older than December 10th)
The release is still the same version because the code hasn't changed. I just made a mistake in the archive.

Well, I can't reproduce the issue. Is there a way I can pm you ? Maybe you could send me your mail ?
