### ISSUE TITLE
Error during init

### ISSUE THREAD

**Issue by kamilmirza** [AZn5ReD/saplearninghub-pdf-downloader-gui#17]
greetings 
I am facing 
`Can't connect :(`
`Error: Error during init`
here's the log:
```Starting script...
(node:8868) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Going to: https://performancemanager.successfactors.eu/sf/learning?company=learninghub
Entering login: kamilmirza@gmail.com
Entering password: ***
Submiting...
Redirected to: https://accounts.sap.com/saml2/idp/usso/Learning_Hub
Can't connect :(
Error: Error during init
    at C:\Users\kamil\Desktop\saplearninghub-pdf-downloader-gui\index.js:18:853146
    at s (C:\Users\kamil\Desktop\saplearninghub-pdf-downloader-gui\index.js:1:1024938)
    at Generator._invoke (C:\Users\kamil\Desktop\saplearninghub-pdf-downloader-gui\index.js:1:1024691)
    at Generator.forEach.e.<computed> [as next] (C:\Users\kamil\Desktop\saplearninghub-pdf-downloader-gui\index.js:1:1025295)
    at t (C:\Users\kamil\Desktop\saplearninghub-pdf-downloader-gui\index.js:1:13893)
    at c (C:\Users\kamil\Desktop\saplearninghub-pdf-downloader-gui\index.js:1:14104)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by AZn5ReD** [comment]
You should probably check the main repo issues : https://github.com/AZn5ReD/saplearninghub-pdf-downloader

Have you tried to login and close the pop up ? If there is none, then I can’t help you unless I have access to your account to debug.

**Comment by kamilmirza** [comment]
I did closed the popup but that didn't help
got it working on Linux though
thanks a lot for this great tool
